---
title: "R5 Rec-Shed Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical-layout: fill
    theme:
      primary: "#217a38"
      secondary: "#24583b"
      success: "#96d4ac"
      info: "#2f5b75"
      warning: "#ffc734"
      danger: "#892f31"
      base_font:
        google: Nunito
      code_font:
        google: Fira Code
      heading_font:
        google: Nunito
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(mapview)
library(here)
library(sf)
library(vroom)
library(dplyr)
library(tidyr)
library(leaflet)
library(ggplot2)
library(scales)
library(tigris)
library(RColorBrewer)
library(zipcodeR)
library(shiny)
library(ggiraph)
library(janitor)
library(tidycensus)
library(stringr)
library(plotly)
# bslib::bs_themer()
```

```{r read in data}
# spatial 
r5_au_bounds <- sf::read_sf(here::here("data/spatial/clean/"))

# ridb
usfs_ridb2021 <- vroom::vroom(here::here("data/ridb/clean/usfs_ridb2021_no_dist_travel.csv"))

# Inyo National Forest subset
inyo_usfs_ridb2021 <- usfs_ridb2021 %>% 
  dplyr::filter(forestname == "Inyo National Forest")
```

## Sidebar {.sidebar}

```{r}
shiny::selectInput("forest", label = "Select a forest:",
                   choices = sort(unique(usfs_ridb2021$forestname)),
                   selected = "Inyo National Forest")
```

## Column 1

### R5 Map

```{r}
# mapview::mapview(r5_au_bounds)

# create subset of park info
park_sub_sf <- usfs_ridb2021 %>% 
  dplyr::group_by(forestname,
                  park,
                  sitetype,
                  facilityzip,
                  facilitylongitude,
                  facilitylatitude) %>%
  dplyr::summarize(n = n()) %>%
  # filter(is.na(sitetype) == TRUE)
  dplyr::select(!n) %>%
  # create as sf object with 4326 crs
  st_as_sf(
    coords = c("facilitylongitude", "facilitylatitude"),
    crs = 4326,
    remove = FALSE
  )

# transform to 4326 crs
r5_bounds <- r5_au_bounds %>% sf::st_as_sf(crs = 4326)

reactive_r5_bounds <- shiny::reactive({
  r5_bounds %>%
    filter(forestname == input$forest)
})

reactive_park <- shiny::reactive({
  park_sub_sf %>% 
    filter(forestname == input$forest)
})

leaflet::renderLeaflet({
  
  camping_icon <- makeIcon(
    here("images/camping_location_icon.png"),
    iconWidth = 25,
    iconHeight = 25
  )
  
  leaflet() %>%
    addPolygons(
      data = reactive_r5_bounds(),
      weight = 1,
      popup = paste0(reactive_r5_bounds()$forestname)
    ) %>%
    addMarkers(
      lng = reactive_park()$facilitylongitude,
      lat = reactive_park()$facilitylatitude,
      popup = paste0(reactive_park()$park,
                     "<br>",
                     "Type of site: ",
                     reactive_park()$sitetype),
      icon = camping_icon
    ) %>% 
    addProviderTiles(providers$CartoDB.Voyager)
})
```


## Column 2
 
### US Visitorshed Map

```{r}

# zip code state info using `zipcodeR`
zip_sub <- zipcodeR::zip_code_db %>% 
  select(
    zipcode,
    state
  )

# joined customer state info
state_zip_usfs_ridb2021 <- left_join(usfs_ridb2021, zip_sub, 
                                     by = c("customerzip" = "zipcode")) %>% 
  rename(customerstate = state) %>% 
  relocate(customerstate, .before = totalpaid)

# state geoms
df_state_geometries_us <- tigris::states() %>% # defaults to 2021 data
  select(STUSPS, geometry) %>%
  rename(state_abbrev = STUSPS) %>%
  rmapshaper::ms_simplify(keep = 0.005, keep_shapes = TRUE)

# summarize ridb2021 data
summary_state_zip_usfs_ridb2021 <- state_zip_usfs_ridb2021 %>% 
  group_by(forestname,
           customerstate) %>% 
  summarize(count = n())

# join data
map_data <- df_state_geometries_us %>% 
  left_join(summary_state_zip_usfs_ridb2021,
            by = c("state_abbrev" = "customerstate")) %>%
  st_transform(crs = 4326)

# reactive df
reactive_map_data <- shiny::reactive({
  map_data %>%
    filter(forestname == input$forest)
})

# map
leaflet::renderLeaflet({
  bins <- c(0, 10, 50, 100, 200, 500, 800, 1000, 2000, 5000, 150000)
  pal <- colorBin("YlOrRd", domain = reactive_map_data()$count, bins = bins)
  
  leaflet() %>%
    setView(lat = 49.850033,
            lng = -118.6500523,
            zoom = 2) %>%
    addPolygons(
      data = reactive_map_data(),
      weight = 1,
      opacity = 1,
      fillColor = ~ pal(count),
      fillOpacity = 0.7,
      color = "white",
      popup = paste0(
        reactive_map_data()$state_abbrev,
        "<br>",
        "Total counts of visits: ",
        reactive_map_data()$count
      )
    ) %>%
    addProviderTiles(providers$CartoDB.Voyager)
})
```

### Visitor Data

```{r}

```


